version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map the container's port 3000 to the host's port 3000
    volumes:
      - ./react-app:/app # Mount the local react-app directory into the container
    environment:
      - NODE_ENV=development # Set the Node environment to development
    stdin_open: true
    tty: true

  word-processor-server: 
    image: syncfusion/word-processor-server:latest 
    environment: 
      #Provide your license key for activation
      SYNCFUSION_LICENSE_KEY: ORg4AjUWIQA/Gnt2UFhhQlJBfVldXHxLflFyVWJYdV54fldBcC0sT3RfQFljTH5Rd0RjUH1bd3NVQw==
    ports:
    - "6002:80"
